#include "icad/agent/workflow.hpp"

#include "icad/agent_templates.hpp"
#include "icad/ai/inspector.hpp"
#include "icad/cad/analysis.hpp"
#include "icad/cad/intersection.hpp"
#include "icad/cad/topology.hpp"
#include "icad/compiler/compiler.hpp"
#include "icad/constraints/validator.hpp"
#include "icad/json/value.hpp"
#include "icad/manufacturing/validator.hpp"

#include <algorithm>
#include <cctype>
#include <sstream>
#include <string>
#include <unordered_set>
#include <vector>

namespace icad::agent {
namespace {

[[nodiscard]] auto object(std::initializer_list<json::Value::Object::value_type> values)
    -> json::Value {
    return json::Value{json::Value::Object{values}};
}

[[nodiscard]] auto array(std::initializer_list<json::Value> values) -> json::Value {
    return json::Value{json::Value::Array{values}};
}

[[nodiscard]] auto strings(const std::vector<std::string>& values) -> json::Value {
    json::Value::Array result;
    result.reserve(values.size());
    for (const auto& value : values) {
        result.emplace_back(value);
    }
    return json::Value{std::move(result)};
}

[[nodiscard]] auto lowercase(std::string_view text) -> std::string {
    std::string result{text};
    std::ranges::transform(result, result.begin(),
                           [](unsigned char character) { return static_cast<char>(std::tolower(character)); });
    return result;
}

[[nodiscard]] auto source_comment(std::string_view text) -> std::string {
    std::string result;
    result.reserve(std::min<std::size_t>(text.size(), 512));
    for (const char raw_character : text) {
        const auto character = static_cast<unsigned char>(raw_character);
        if (result.size() == 512)
            break;
        if (character == '\n' || character == '\r' || character == '\t' ||
            character < 0x20U || character == 0x7fU) {
            result.push_back(' ');
        } else {
            result.push_back(static_cast<char>(character));
        }
    }
    return result;
}

[[nodiscard]] auto generic_source() -> std::string {
    return R"ICAD(# Agent-ready parametric starter generated by ICAD.
PROJECT agent_design
UNITS mm
PARAMETER width 100 mm
PARAMETER depth 60 mm
PARAMETER height 20 mm
MATERIAL finish
PRESET ALUMINUM
ROUGHNESS 0.3
TEXTURE_SCALE 10 mm
UV_MODE BOX
END
BODY main_body
MATERIAL finish
FEATURE base
TYPE BOX
WIDTH width
DEPTH depth
HEIGHT height
END
END
)ICAD";
}

[[nodiscard]] auto requirements(DesignIntent intent) -> json::Value {
    if (intent == DesignIntent::robotic_arm) {
        return array({"10 named component bodies", "10-joint mechanism graph",
                      "9 driven degrees of freedom", "joint limits and animated inspection scene",
                      "manufacturing materials and embedded textures",
                      "STEP assembly plus STL, OBJ, glTF/GLB, 3MF, drawings, BOM, and viewer"});
    }
    if (intent == DesignIntent::bridge) {
        return array({"parametric 120 m bridge", "35 native solids", "structural material ownership",
                      "inspection animation", "complete engineering and viewer artifact package"});
    }
    return array({"parameterized dimensions", "named material", "validated closed solid",
                  "complete engineering and viewer artifact package"});
}

[[nodiscard]] auto editable_parameters(const compiler::ir::Project& project) -> json::Value {
    json::Value::Array handles;
    handles.reserve(project.parameters.size());
    for (const auto& parameter : project.parameters) {
        handles.push_back(object({{"name", parameter.name},
                                  {"value", parameter.value.value},
                                  {"unit", parameter.value.unit},
                                  {"expression", parameter.expression},
                                  {"dependencies", strings(parameter.dependencies)}}));
    }
    return json::Value{std::move(handles)};
}

[[nodiscard]] auto editable_angles(const compiler::ir::Project& project) -> json::Value {
    json::Value::Array handles;
    handles.reserve(project.angles.size());
    for (const auto& angle : project.angles) {
        handles.push_back(object({{"name", angle.name},
                                  {"value", angle.degrees},
                                  {"unit", "deg"}}));
    }
    return json::Value{std::move(handles)};
}

[[nodiscard]] auto prompt_understanding(std::string_view normalized, DesignIntent intent)
    -> json::Value {
    json::Value::Array signals;
    json::Value::Array assumptions;
    std::string_view selected_template = "generic_part";
    std::string_view source_reference = "embedded generic parametric starter";
    if (intent == DesignIntent::robotic_arm) {
        selected_template = "robotic_arm";
        source_reference = "examples/Robotic_Arm_3D_Model";
        signals.emplace_back("articulated robotic manipulator");
        if (normalized.contains("gripper"))
            signals.emplace_back("end-effector gripper");
        if (normalized.contains("animat"))
            signals.emplace_back("programmable articulation scene");
        if (normalized.contains("industrial"))
            signals.emplace_back("industrial material and manufacturing package");
        assumptions.emplace_back("10 named component bodies and 25 closed solids");
        assumptions.emplace_back("9 driven degrees of freedom with explicit joint limits");
        assumptions.emplace_back("millimetre dimensions and deterministic embedded materials");
        assumptions.emplace_back("default link dimensions remain editable through named parameters");
    } else if (intent == DesignIntent::bridge) {
        selected_template = "advanced_bridge";
        source_reference = "examples/advanced.icad";
        signals.emplace_back("multi-span structural bridge");
        assumptions.emplace_back("120 metre acceptance span with 35 closed solids");
        assumptions.emplace_back("structural materials, inspection scene, drawings, and BOM");
    } else {
        signals.emplace_back("generic parametric solid");
        assumptions.emplace_back("rectangular starter topology");
        assumptions.emplace_back("100 x 60 x 20 mm default envelope");
        assumptions.emplace_back("aluminum finish with deterministic embedded texture");
    }
    return object({{"selectedTemplate", std::string{selected_template}},
                   {"sourceReference", std::string{source_reference}},
                   {"recognizedSignals", json::Value{std::move(signals)}},
                   {"explicitAssumptions", json::Value{std::move(assumptions)}}});
}

[[nodiscard]] auto selected(const json::Value& source, std::string_view name) -> json::Value {
    const auto* value = source.find(name);
    return value == nullptr ? json::Value{nullptr} : *value;
}

auto add_concept_token(json::Value::Array& tokens, std::unordered_set<std::string>& seen,
                       std::string token) -> void {
    if (seen.insert(token).second)
        tokens.emplace_back(std::move(token));
}

[[nodiscard]] auto compressed_prompt_tokens(std::string_view prompt) -> json::Value {
    const auto normalized = lowercase(prompt);
    json::Value::Array tokens;
    std::unordered_set<std::string> seen;
    const auto match = [&](std::string_view needle, std::string token) {
        if (normalized.contains(needle))
            add_concept_token(tokens, seen, std::move(token));
    };
    if (normalized.contains("create") || normalized.contains("make") ||
        normalized.contains("build") || normalized.contains("design"))
        add_concept_token(tokens, seen, "ACTION:DESIGN");
    match("robot", "DOMAIN:ROBOTIC_MANIPULATOR");
    match("bridge", "DOMAIN:BRIDGE");
    match("assembly", "STRUCTURE:ASSEMBLY");
    match("grip", "FUNCTION:MECHANICAL_GRIP");
    match("claw", "FUNCTION:MECHANICAL_GRIP");
    match("vacuum", "FUNCTION:VACUUM_PICK");
    match("suction", "FUNCTION:VACUUM_PICK");
    match("vision", "FUNCTION:VISION_GUIDANCE");
    match("camera", "FUNCTION:VISION_GUIDANCE");
    match("weld", "FUNCTION:WELDING");
    match("mill", "FUNCTION:MACHINING");
    match("animate", "MOTION:PROGRAMMABLE_SCENE");
    match("scene", "MOTION:PROGRAMMABLE_SCENE");
    match("revolute", "MOTION:REVOLUTE");
    match("rotate", "MOTION:REVOLUTE");
    match("prismatic", "MOTION:PRISMATIC");
    match("slide", "MOTION:PRISMATIC");
    match("aluminum", "MATERIAL:ALUMINUM");
    match("aluminium", "MATERIAL:ALUMINUM");
    match("steel", "MATERIAL:STRUCTURAL_STEEL");
    match("rubber", "MATERIAL:RUBBER");
    match("glass", "MATERIAL:GLASS");
    match("industrial", "QUALITY:INDUSTRIAL");
    match("manufactur", "QUALITY:MANUFACTURABLE");
    match("detail", "QUALITY:HIGH_DETAIL");
    match("precise", "QUALITY:PRECISION");
    match("tolerance", "CONTROL:TOLERANCE");
    match("constraint", "CONTROL:CONSTRAINTS");
    match("orthographic", "VIEW:ORTHOGRAPHIC");
    match("section", "VIEW:SECTION");
    match("auxiliary", "VIEW:AUXILIARY");
    match("step", "OUTPUT:STEP_ASSEMBLY");
    match("stl", "OUTPUT:STL");
    match("obj", "OUTPUT:OBJ");
    match("drawing", "OUTPUT:DRAWING");

    std::istringstream words{std::string{prompt}};
    std::vector<std::string> raw_words;
    for (std::string word; words >> word;)
        raw_words.push_back(std::move(word));
    constexpr std::array units{"mm", "cm", "m", "in", "inch", "inches", "deg", "degree",
                               "degrees", "s", "fps"};
    for (std::size_t index = 0; index < raw_words.size(); ++index) {
        if (!std::ranges::any_of(raw_words[index], [](unsigned char character) {
                return std::isdigit(character) != 0;
            })) {
            continue;
        }
        std::string quantity = "VALUE:" + raw_words[index];
        if (index + 1 < raw_words.size()) {
            auto possible_unit = lowercase(raw_words[index + 1]);
            while (!possible_unit.empty() &&
                   !std::isalnum(static_cast<unsigned char>(possible_unit.back())))
                possible_unit.pop_back();
            if (std::ranges::find(units, possible_unit) != units.end())
                quantity += possible_unit;
        }
        add_concept_token(tokens, seen, std::move(quantity));
    }
    if (tokens.empty())
        tokens.emplace_back("ACTION:CONCEPTUALIZE");
    return json::Value{std::move(tokens)};
}

[[nodiscard]] auto design_map(const compiler::ir::Project& project) -> json::Value {
    const auto parsed = json::parse(ai::project_json(project));
    if (!parsed.ok())
        return object({{"schema", "icad.agent.design-map.v1"}, {"available", false}});
    const auto& inspection = *parsed.value;
    return object({
        {"schema", "icad.agent.design-map.v1"},
        {"available", true},
        {"coordinateSystem", "+X forward, +Y lateral, +Z up; millimetres and degrees"},
        {"revision", selected(inspection, "revision")},
        {"overall", selected(inspection, "metrics")},
        {"bodies", selected(inspection, "bodies")},
        {"spatial", selected(inspection, "spatial")},
        {"mechanism", selected(inspection, "mechanism")},
        {"constraints", selected(inspection, "constraints")},
        {"mates", selected(inspection, "mates")},
        {"contacts", selected(inspection, "intersections")},
        {"scenes", selected(inspection, "scenes")},
        {"readingOrder", array({"overall bounds", "body centers and sizes",
                                 "named points and vectors", "parent-child joints",
                                 "constraints and mates", "contacts and clearances",
                                 "animation tracks"})},
    });
}

} // namespace

auto intent_name(DesignIntent intent) -> std::string_view {
    if (intent == DesignIntent::robotic_arm)
        return "ROBOTIC_ARM";
    if (intent == DesignIntent::bridge)
        return "BRIDGE";
    return "GENERIC_PART";
}

auto conceptualize_json(std::string_view prompt) -> std::string {
    const auto prompt_copy = source_comment(prompt);
    std::size_t raw_words = 0;
    {
        std::istringstream words{prompt_copy};
        for (std::string word; words >> word;)
            ++raw_words;
    }
    auto compressed = compressed_prompt_tokens(prompt_copy);
    const auto compressed_count = compressed.array() == nullptr ? std::size_t{0}
                                                                 : compressed.array()->size();
    const double compression_ratio = raw_words == 0
                                         ? 1.0
                                         : static_cast<double>(compressed_count) /
                                               static_cast<double>(raw_words);
    return json::serialize(object({
        {"schema", "icad.agent.concept.v1"},
        {"conceptualIterations", 1.0},
        {"rawInput", prompt_copy},
        {"rawWordCount", static_cast<double>(raw_words)},
        {"compressedTokenCount", static_cast<double>(compressed_count)},
        {"compressionRatio", compression_ratio},
        {"compressedTokens", std::move(compressed)},
        {"blueprintReading", object({
             {"titleBlock", array({"design identity", "units and scale", "material callouts",
                                    "general tolerances", "notes and revision"})},
             {"billOfMaterials", array({"named components", "quantity", "material",
                                         "assembly ownership"})},
             {"dimensions", array({"size dimensions", "location dimensions",
                                    "linear and angular tolerances", "diameter and radius"})},
             {"views", array({"choose primary view with clearest detail and least hidden lines",
                               "use sufficient front/top/side orthographic views",
                               "use section view for hidden internal detail",
                               "use auxiliary view for true inclined-surface shape"})},
         })},
        {"conceptualRequest",
         "Expand the compressed tokens once into a complete component hierarchy, spatial envelope, "
         "size/location dimensions, materials, kinematic graph, constraints, manufacturing intent, "
         "and inspection scene. Then emit only dependency-ordered ICAD grammar."},
        {"outputContract", object({
             {"format", "ICAD_GRAMMAR_ONLY"},
             {"allowMarkdown", false},
             {"allowProse", false},
             {"requiredOrder", array({"PROJECT and UNITS", "PARAMETER and ANGLE",
                                       "POINT3 and VECTOR", "MATERIAL",
                                       "BODY: SKETCH then PAD or POCKET history",
                                       "POSE, JOINT, CONSTRAINT and MATE",
                                       "SCENE, TRACK and KEYFRAME"})},
         })},
        {"visualFeedback", object({{"available", false},
                                    {"requiredSchema", "icad.visual.snapshot.v1"},
                                    {"next", "Compile source and call icad.visualize directly"}})},
        {"iterationProtocol", array({
             "Run this conceptualization pass exactly once",
             "Emit one complete ICAD source document only",
             "Compile and repair stable diagnostics without reconceptualizing",
             "Call icad.visualize and consume icad.visual.snapshot.v1",
             "Revise named parameters, profiles, bodies, joints, or scenes based on view evidence",
             "Repeat compile and visual feedback until silhouette, body identity, bounds, and joints match intent",
             "Run engineering review and build only after visual acceptance",
         })},
    }));
}

auto bootstrap(std::string_view prompt) -> BootstrapResult {
    const auto normalized = lowercase(prompt);
    DesignIntent intent = DesignIntent::generic_part;
    if ((normalized.contains("robot") && normalized.contains("arm")) ||
        normalized.contains("manipulator") || normalized.contains("gripper")) {
        intent = DesignIntent::robotic_arm;
    } else if (normalized.contains("bridge") || normalized.contains("viaduct")) {
        intent = DesignIntent::bridge;
    }
    std::string source;
    if (intent == DesignIntent::robotic_arm)
        source = std::string{templates::robotic_arm};
    else if (intent == DesignIntent::bridge)
        source = std::string{templates::bridge};
    else
        source = generic_source();

    source = "# Agent prompt: " + source_comment(prompt) + "\n# Embedded template: " +
             std::string{intent_name(intent)} + "\n" + source;

    const auto compilation = compiler::compile(source);
    const double confidence = intent == DesignIntent::generic_part ? 0.55 : 0.98;
    const auto plan = object({
        {"schema", "icad.agent.bootstrap.v1"},
        {"prompt", std::string{prompt}},
        {"intent", std::string{intent_name(intent)}},
        {"confidence", confidence},
        {"sourceReady", compilation.ok()},
        {"source", source},
        {"sourceProvenance", "prompt and selected template are embedded as source comments"},
        {"promptUnderstanding", prompt_understanding(normalized, intent)},
        {"acceptanceCriteria", requirements(intent)},
        {"editableParameters", compilation.ok() ? editable_parameters(*compilation.ir_project)
                                                  : json::Value{json::Value::Array{}}},
        {"editableAngles", compilation.ok() ? editable_angles(*compilation.ir_project)
                                              : json::Value{json::Value::Array{}}},
        {"parameterStrategy", "Edit named PARAMETER and ANGLE declarations before changing topology"},
        {"preferredTool", "icad.agent.create"},
        {"nextTool", "icad.agent.review"},
        {"workflow", array({"agent.create"})},
        {"fallbackWorkflow", array({"bootstrap", "review", "project.write", "project.build"})},
        {"expectedModelIterations", intent == DesignIntent::generic_part ? 2.0 : 1.0},
    });
    return {intent, std::move(source), json::serialize(plan)};
}

auto review_json(std::string_view source) -> std::string {
    const auto compilation = compiler::compile(source);
    if (!compilation.ok()) {
        const auto parsed = json::parse(ai::diagnostics_json(source));
        return json::serialize(object({
            {"schema", "icad.agent.review.v1"},
            {"ready", false},
            {"stage", "compile"},
            {"diagnostics", parsed.ok() ? std::move(*parsed.value) : json::Value{nullptr}},
            {"nextActions", array({"Repair only the reported source locations", "Call icad.agent.review again"})},
        }));
    }

    const auto& project = *compilation.ir_project;
    const auto constraint_results = constraints::validate(project);
    const auto manufacturing_report = manufacturing::validate(project);
    const auto topology = cad::build_topology(project);
    const auto topology_validation = cad::validate_topology(topology);
    const auto metrics = cad::analyze(project);
    const auto interference =
        cad::analyze_intersections(project, project.tolerance.linear_mm);
    const bool constraints_passed = constraints::all_passed(constraint_results);
    const bool ready = constraints_passed && manufacturing_report.passed &&
                       topology_validation.valid() && !metrics.parts.empty();

    json::Value::Array failed_constraints;
    for (const auto& constraint : constraint_results) {
        if (!constraint.passed)
            failed_constraints.push_back(object({{"name", constraint.name},
                                                 {"message", constraint.message}}));
    }
    json::Value::Array manufacturing_issues;
    for (const auto& issue : manufacturing_report.issues) {
        manufacturing_issues.push_back(object({{"code", issue.code}, {"subject", issue.subject},
                                                {"message", issue.message}}));
    }
    json::Value::Array actions;
    if (!constraints_passed)
        actions.emplace_back("Repair failed constraints using named points, vectors, angles, or parameters");
    if (!manufacturing_report.passed)
        actions.emplace_back("Resolve manufacturing errors before export");
    if (!topology_validation.valid())
        actions.emplace_back("Repair invalid topology before export");
    if (interference.penetrating_part_pairs != 0)
        actions.emplace_back("Review reported assembly penetrations; joint hardware overlap may be intentional");
    if (ready)
        actions.emplace_back("Commit the exact source revision and call icad.project.build");

    return json::serialize(object({
        {"schema", "icad.agent.review.v1"},
        {"ready", ready},
        {"stage", ready ? "build" : "engineering"},
        {"project", project.name},
        {"summary", object({{"bodies", static_cast<double>(project.bodies.size())},
                             {"instances", static_cast<double>(project.instances.size())},
                             {"joints", static_cast<double>(project.joints.size())},
                             {"degreesOfFreedom", static_cast<double>(std::ranges::count_if(
                                 project.joints, [](const auto& joint) {
                                     return joint.kind != compiler::ir::JointKind::fixed;
                                 }))},
                             {"solids", static_cast<double>(topology.solids.size())},
                             {"exactFaces", static_cast<double>(topology.face_count())},
                             {"volumeMm3", metrics.volume_mm3}})},
        {"checks", object({{"constraintsPassed", constraints_passed},
                            {"manufacturingPassed", manufacturing_report.passed},
                            {"topologyValid", topology_validation.valid()},
                            {"penetratingPartPairs",
                             static_cast<double>(interference.penetrating_part_pairs)},
                            {"surfaceContactOnlyPartPairs",
                             static_cast<double>(interference.surface_contact_only_part_pairs)}})},
        {"failedConstraints", json::Value{std::move(failed_constraints)}},
        {"manufacturingIssues", json::Value{std::move(manufacturing_issues)}},
        {"designMap", design_map(project)},
        {"nextActions", json::Value{std::move(actions)}},
    }));
}

} // namespace icad::agent
