program          = { requirement | statement | newline } ;
requirement      = "REQUIRES", ( "ICAD", language_version |
                                  "CAPABILITY", identifier ), newline ;
language_version = digit, { digit }, ".", digit, { digit } ;
statement        = project | units | parameter | angle | point3 | vector | pose | instance | joint |
                   interface | connection | tolerance | material | profile | sketch | body |
                   constraint | mate | scene ;

project          = "PROJECT", identifier, newline ;
units            = "UNITS", identifier, newline ;
parameter        = "PARAMETER", identifier, scalar_expression, newline ;
angle            = "ANGLE", identifier, scalar_expression, newline ;
tolerance        = "TOLERANCE", "LINEAR", scalar_value,
                   "ANGULAR", scalar_value, newline ;
point3           = "POINT3", identifier,
                   ( scalar_value, scalar_value, scalar_value |
                     "FROM", identifier, "ALONG", identifier, "DISTANCE", scalar_value ), newline ;
vector           = "VECTOR", identifier,
                   ( number, number, number |
                     "FROM", identifier, "TO", identifier |
                     "ROTATE", identifier, "AROUND", identifier, "BY", scalar_value ), newline ;
pose             = "POSE", identifier, "AT", identifier, "ROTATION",
                   scalar_value, scalar_value, scalar_value, newline ;
instance         = "INSTANCE", identifier, "OF", identifier, "AT", identifier,
                   "ROTATION", scalar_value, scalar_value, scalar_value, newline ;
joint            = "JOINT", identifier, joint_kind, identifier, identifier,
                   "AT", identifier, "AXIS", identifier, [ joint_drive ], newline ;
joint_kind       = "FIXED" | "REVOLUTE" | "PRISMATIC" ;
joint_drive      = "VALUE", scalar_value, "LIMIT", scalar_value, scalar_value ;
interface        = "INTERFACE", identifier, "BODY", identifier, "AT", identifier,
                   "AXIS", identifier, "TYPE", interface_kind,
                   [ "SIZE", scalar_value ], newline ;
interface_kind   = "MOUNT" | "FLANGE" | "SHAFT" | "BORE" | "PIN" | "HOLE" |
                   "BEARING_SEAT" | "WELD_SEAM" | "BOND_FACE" | "DATUM" ;
connection       = "CONNECT", identifier, identifier, identifier, "METHOD",
                   connection_method,
                   { "STANDARD", identifier | "FASTENER", identifier |
                     "FIT", identifier | "CLEARANCE", scalar_value | "AUTO" }, newline ;
connection_method = "BOLTED" | "SCREWED" | "PINNED" | "PRESS_FIT" |
                    "SLIP_FIT" | "BEARING" | "WELDED" | "BRAZED" | "BONDED" ;
material         = "MATERIAL", identifier,
                   ( identifier, newline |
                     newline, "PRESET", identifier, newline,
                     [ "BASE_COLOR", number, number, number, number, newline ],
                     [ "METALLIC", number, newline ],
                     [ "ROUGHNESS", number, newline ],
                     [ "TEXTURE_SCALE", quantity, newline ],
                     [ "UV_MODE", ( "BOX" | "PLANAR" | "CYLINDRICAL" | "SPHERICAL" ), newline ],
                     "END", newline ) ;
profile          = "PROFILE", identifier, newline,
                   ( point_profile | path_profile | circle_profile ), "END", newline ;
point_profile    = point, point, point, { point } ;
point            = "POINT", quantity, quantity, newline ;
path_profile     = "START", quantity, quantity, newline,
                   path_segment, { path_segment }, "CLOSE", newline ;
path_segment     = line_segment | arc_segment ;
line_segment     = "LINE", quantity, quantity, newline ;
arc_segment      = "ARC", quantity, quantity, "CENTER", quantity, quantity,
                   ( "CW" | "CCW" ), newline ;
circle_profile   = "CIRCLE", quantity, quantity, quantity, newline ;

sketch           = "SKETCH", identifier, newline,
                   sketch_contents,
                   "END", newline ;
body_sketch      = "SKETCH", identifier, "ON",
                   ( "PLANE", sketch_plane |
                     "FACE", ( identifier, [ face_selector ] |
                               persistent_face_reference ) ), newline,
                   sketch_contents,
                   "END", newline ;
sketch_contents  = sketch_circle |
                   { sketch_point | sketch_entity | sketch_constraint } |
                   shape, { shape | region | sketch_constraint }, [ solve_requirement ] ;
sketch_plane     = "XY" | "XZ" | "YZ" ;
sketch_circle    = "CIRCLE", scalar_value, scalar_value, scalar_value, newline ;
sketch_point     = "POINT", identifier, scalar_value, scalar_value,
                   [ "FIXED" ], newline ;
sketch_entity    = sketch_line | sketch_arc ;
sketch_line      = "LINE", identifier, "FROM", identifier, "TO", identifier, newline ;
sketch_arc       = "ARC", identifier, "FROM", identifier, "TO", identifier,
                   "CENTER", identifier, ( "CW" | "CCW" ), newline ;
shape            = "SHAPE", identifier, ( "OPEN" | "CLOSED" ), "ROLE", shape_role,
                   newline, { shape_point | shape_entity }, "END", newline ;
shape_role       = "STOCK" | "ADDITIVE" | "HOLE" | "CONSTRUCTION" ;
shape_point      = sketch_point ;
shape_entity     = sketch_line | sketch_arc | shape_circle ;
shape_circle     = "CIRCLE", identifier, "CENTER", identifier, "RADIUS",
                   scalar_value, newline ;
region           = "REGION", identifier, newline,
                   "OUTER", identifier, newline,
                   [ "HOLES", identifier, { identifier }, newline ],
                   "END", newline ;
solve_requirement = "SOLVE", ( "FULL" | "ALLOW_UNDER" ), newline ;
sketch_constraint = "CONSTRAINT", identifier,
                    ( ( "HORIZONTAL" | "VERTICAL" | "COINCIDENT" ),
                      qualified_name, qualified_name |
                      ( "DISTANCE" | "H_DISTANCE" | "V_DISTANCE" ),
                      qualified_name, qualified_name, scalar_value |
                      "ANGLE", qualified_name, qualified_name, qualified_name,
                      scalar_value |
                      ( "PARALLEL" | "PERPENDICULAR" | "EQUAL_LENGTH" |
                        "CONCENTRIC" | "EQUAL_RADIUS" ),
                      qualified_name, qualified_name |
                      "MIDPOINT", qualified_name, qualified_name |
                      "SYMMETRIC", qualified_name, qualified_name, "ABOUT",
                      qualified_name |
                      "TANGENT", qualified_name, qualified_name, "AT",
                      qualified_name ), newline ;

body             = "BODY", identifier, newline,
                   [ "MATERIAL", identifier, newline ],
                   { face_reference | topology_selection | body_sketch | pad | pocket | feature },
                   "END", newline ;
face_reference   = "FACE", identifier, "FROM", persistent_face_reference, newline ;
persistent_face_reference = identifier, ".", "face", ".", ( "top" | "bottom" ) ;
topology_selection = "SELECTION", identifier, newline,
                   "FROM", identifier, newline,
                   "EDGES", "WHERE", newline,
                   "LOOP", newline,
                   "CIRCULAR", newline,
                   ( "CONCAVE" | "CONVEX" ), newline,
                   "ADJACENT_TO", "FACE", ( "top" | "bottom" ), newline,
                   "END", newline ;
pad              = "PAD", identifier, "FROM", region_reference, "DEPTH", scalar_value,
                   ( "NEW" | "ADD" ), newline ;
pocket           = "POCKET", identifier, "FROM", region_reference, "DEPTH",
                   scalar_value, newline ;
region_reference = identifier, [ ".", identifier ] ;
feature          = "FEATURE", identifier, newline,
                   "TYPE", identifier, newline,
                   [ "PROFILE", identifier, newline ],
                   [ "TARGET_PROFILE", identifier, newline ],
                   [ "PATH", identifier, identifier, { identifier }, newline ],
                   [ "OPERATION", ( "NEW" | "UNION" | "CUT" | "INTERSECT" ), newline ],
                   [ "SELECT",
                     ( "EDGE", ( "NEAREST", identifier |
                                 ( "TOP" | "BOTTOM" ), ( "INNER" | "OUTER" ) ) |
                       "EDGESET", identifier ), newline ],
                   [ "DIRECTION", identifier, newline ],
                   [ "COUNT", number, newline ],
                   [ "PLANE", identifier, "NORMAL", identifier, newline ],
                   { property }, "END", newline ;
property         = identifier, scalar_expression, newline ;
constraint       = "CONSTRAINT", identifier,
                   ( "MIN_DISTANCE", identifier, identifier, scalar_value |
                     "COINCIDENT", identifier, identifier, scalar_value |
                     "PARALLEL", identifier, identifier |
                     "PERPENDICULAR", identifier, identifier |
                     "ANGLE_BETWEEN", identifier, identifier, scalar_value ), newline ;
mate             = "MATE", identifier,
                   ( "FACE", identifier, face_selector, identifier, face_selector,
                     "OFFSET", scalar_value |
                     "EDGE", identifier, edge_selector, identifier, edge_selector,
                     "TOLERANCE", scalar_value ), newline ;
face_selector    = "X_MIN" | "X_MAX" | "Y_MIN" | "Y_MAX" | "Z_MIN" | "Z_MAX" ;
edge_selector    = ( "X_AT_Y_MIN_Z_MIN" | "X_AT_Y_MIN_Z_MAX" |
                     "X_AT_Y_MAX_Z_MIN" | "X_AT_Y_MAX_Z_MAX" |
                     "Y_AT_X_MIN_Z_MIN" | "Y_AT_X_MIN_Z_MAX" |
                     "Y_AT_X_MAX_Z_MIN" | "Y_AT_X_MAX_Z_MAX" |
                     "Z_AT_X_MIN_Y_MIN" | "Z_AT_X_MIN_Y_MAX" |
                     "Z_AT_X_MAX_Y_MIN" | "Z_AT_X_MAX_Y_MAX" ) ;

scene            = "SCENE", identifier, newline,
                   "DURATION", quantity, newline,
                   "FPS", number, newline,
                   "BACKGROUND", identifier, newline,
                   [ "LOOP", number, newline ],
                   { light | event },
                   { track }, "END", newline ;
light            = "LIGHT", identifier, ( "DIRECTIONAL" | "POINT" ),
                   "COLOR", number, number, number, "INTENSITY", number,
                   [ "AT", identifier ], newline ;
event            = "EVENT", quantity, identifier, newline ;
track            = "TRACK", identifier,
                   ( "BODY" | "CAMERA" | "JOINT" | "VISIBILITY" ), identifier, newline,
                   [ "EASING", ( "LINEAR" | "EASE_IN" | "EASE_OUT" |
                                  "EASE_IN_OUT" | "STEP" ), newline ],
                   keyframe, keyframe, { keyframe }, "END", newline ;
keyframe         = "KEYFRAME", quantity,
                   ( "POSITION", quantity, quantity, quantity,
                     "ROTATION", quantity, quantity, quantity |
                     "VALUE", scalar_value |
                     "VISIBLE", ( "ON" | "OFF" ) ), newline ;

quantity         = number, identifier ;
scalar_value     = quantity | qualified_name ;
scalar_expression = additive_expression ;
additive_expression = multiplicative_expression,
                      { ( "+" | "-" ), multiplicative_expression } ;
multiplicative_expression = unary_expression,
                            { ( "*" | "/" ), unary_expression } ;
unary_expression = [ "+" | "-" ], primary_expression ;
primary_expression = number, [ identifier ] | qualified_name |
                     "(", scalar_expression, ")" ;
qualified_name   = identifier, { ".", identifier } ;
identifier       = letter, { letter | digit | "_" } ;
number           = [ "-" ], digit, { digit }, [ ".", digit, { digit } ] ;
newline          = "\n" ;
letter           = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" |
                   "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" |
                   "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" |
                   "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" |
                   "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" |
                   "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" ;
digit            = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
