#define WEBVIEW_HEADER
#include <webview/webview.h>

#include <cctype>
#include <filesystem>
#include <iostream>
#include <string>
#include <string_view>

namespace {

[[nodiscard]] auto file_url(const std::filesystem::path& path) -> std::string {
    const auto absolute = std::filesystem::absolute(path).lexically_normal().generic_string();
    std::string encoded;
    encoded.reserve(absolute.size() + 16);
    constexpr char hex[] = "0123456789ABCDEF";
    for (const char raw_character : absolute) {
        const auto character = static_cast<unsigned char>(raw_character);
        const bool safe = std::isalnum(character) != 0 || character == '/' || character == ':' ||
                          character == '-' || character == '_' || character == '.' ||
                          character == '~';
        if (safe) {
            encoded.push_back(static_cast<char>(character));
        } else {
            encoded.push_back('%');
            encoded.push_back(hex[(character >> 4U) & 0x0FU]);
            encoded.push_back(hex[character & 0x0FU]);
        }
    }
#ifdef _WIN32
    return "file:///" + encoded;
#else
    return "file://" + encoded;
#endif
}

auto usage(std::ostream& output) -> void {
    output << "Usage: icad-viewer <compiled.html>\n"
              "Open a self-contained HTML viewer generated by `icad build`.\n";
}

} // namespace

auto main(int argc, char** argv) -> int {
    if (argc != 2 || std::string_view{argv[1]} == "--help" ||
        std::string_view{argv[1]} == "-h") {
        usage(argc == 2 ? std::cout : std::cerr);
        return argc == 2 ? 0 : 2;
    }

    const std::filesystem::path document{argv[1]};
    if (!std::filesystem::is_regular_file(document) || document.extension() != ".html") {
        std::cerr << "icad-viewer: expected an existing compiled .html file: " << document << '\n';
        return 2;
    }

    const auto window = webview_create(1, nullptr);
    if (window == nullptr) {
        std::cerr << "icad-viewer: could not initialize the platform webview\n";
        return 1;
    }
    const auto title = "ICAD Viewer - " + document.stem().string();
    const auto url = file_url(document);
    const auto title_result = webview_set_title(window, title.c_str());
    const auto size_result = webview_set_size(window, 1280, 800, WEBVIEW_HINT_NONE);
    const auto navigate_result = webview_navigate(window, url.c_str());
    if (title_result != WEBVIEW_ERROR_OK || size_result != WEBVIEW_ERROR_OK ||
        navigate_result != WEBVIEW_ERROR_OK) {
        std::cerr << "icad-viewer: failed to configure the viewer window\n";
        webview_destroy(window);
        return 1;
    }
    const auto run_result = webview_run(window);
    const auto destroy_result = webview_destroy(window);
    return run_result == WEBVIEW_ERROR_OK && destroy_result == WEBVIEW_ERROR_OK ? 0 : 1;
}
